module.exports = [
  {},
  {
    "website": "https://www.siam.org/conferences/cm/conference/sdm24",
    "title": "SDM",
    "conference": "Data Mining",
    "location": "Houston, Texas, USA",
    "date": "18-20 April 2023",
    "notification": "late December 2023",
    "final": "",
    "registration": "18 March 2024",
    "remark": ""
  },
  {
    "website": "https://recomb.org/recomb2024/",
    "title": "RECOMB",
    "conference": "Research in Computational Molecular Biology",
    "location": "Boston, Massachusetts, USA",
    "date": "29 April - 2 May 2024",
    "notification": "22 December 2023",
    "final": "26 January 2024",
    "registration": "15 March 2024",
    "remark": ""
  },
  {
    "website": "https://www.aamas2024-conference.auckland.ac.nz/",
    "title": "AAMAS",
    "conference": "Autonomous Agents and Multiagent Systems",
    "location": "Auckland, New Zealand",
    "date": "6-10 May 2024",
    "notification": "20 December 2023",
    "final": "8 February 2024",
    "registration": "11 April 2024",
    "remark": ""
  },
  {
    "website": "https://tamc2024.comp.polyu.edu.hk/",
    "title": "TAMC",
    "conference": "Theory and Applications of Models of Computation",
    "location": "Hong Kong, SAR China",
    "date": "13-15 May 2024",
    "notification": "1 February 2024",
    "final": "",
    "registration": "31 March 2024",
    "remark": ""
  },
  {
    "website": "https://ola2024.sciencesconf.org/",
    "title": "OLA",
    "conference": "Optimization and Learning",
    "location": "Dubrovnik, Croatia",
    "date": "13-15 May 2024",
    "notification": "9 February 2024",
    "final": "",
    "registration": "31 March 2024",
    "remark": "early registration obligatory for authors"
  },
  {
    "website": "https://conf.researchr.org/home/flops-2024",
    "title": "FLOPS",
    "conference": "Functional and Logic Programming",
    "location": "Kumamoto, Japan",
    "date": "15-17 May 2024",
    "notification": "26 January 2024",
    "final": "21 February 2024",
    "registration": "30 April 2024",
    "remark": ""
  },
  {
    "website": "https://eventos.ull.es/isco-2024",
    "title": "ISCO",
    "conference": "International Symposium on Combinatorial Optimization",
    "location": "Tenerife, Canary Islands, Spain",
    "date": "22-24 May 2024",
    "notification": "15 March 2024",
    "final": "15 April 2024",
    "registration": "31 March 2024",
    "remark": "school 20-21 May 2024"
  },
  {
    "website": "https://eurocrypt.iacr.org/2024/",
    "title": "EUROCRYPT",
    "conference": "Theory and Applications of Cryptographic Techniques",
    "location": "Zurich, Switzerland",
    "date": "26-30 May 2024",
    "notification": "8 December 2023<br>31 January 2024",
    "final": "",
    "registration": "26 April 2024",
    "remark": ""
  },
  {
    "website": "https://easychair.org/smart-program/LPAR2024/",
    "title": "LPAR",
    "conference": "Logic for Programming, Artificial Intelligence and Reasoning",
    "location": "Mauritius",
    "date": "26-31 May 2024",
    "notification": "1 April 2024",
    "final": "5 April 2024",
    "registration": "16 May 2024",
    "remark": ""
  },
  {
    "website": "http://sirocco2024.di.unisa.it/",
    "title": "SIROCCO",
    "conference": "Structural Information and Communication Complexity",
    "location": "Vietri sul Mare, Salerno, Italy",
    "date": "27-29 May 2024",
    "notification": "28 January 2024",
    "final": "",
    "registration": "31 March 2024",
    "remark": ""
  },
  {
    "website": "https://sites.google.com/view/cpaior2024",
    "title": "CPAIOR",
    "conference": "Integration of Constraint Programming, Artificial Intelligence, and Operations Research",
    "location": "Uppsala, Sweden",
    "date": "28-31 May 2024",
    "notification": "1 February 2024",
    "final": "",
    "registration": "15 April 2024",
    "remark": ""
  },
  {
    "website": "https://icaps24.icaps-conference.org/",
    "title": "ICAPS",
    "conference": "International Conference on Automated Planning and Scheduling",
    "location": "Banf, Alberta, Canada",
    "date": "1-5 June 2024",
    "notification": "12 February 2024",
    "final": "",
    "registration": "31 March 2024",
    "remark": ""
  },
  {
    "website": "https://halg2024.ideas-ncbr.pl/",
    "title": "HALG",
    "conference": "Highlights of Algorithms",
    "location": "Warsaw, Poland",
    "date": "3-5 June 2024",
    "notification": "",
    "final": "25 May 2024",
    "registration": "1 May 2024",
    "remark": ""
  },
  {
    "website": "https://conf.researchr.org/home/nfm-2024",
    "title": "NFM",
    "conference": "NASA Formal Methods",
    "location": "Moffett Field, California, USA",
    "date": "4-6 June 2024",
    "notification": "16 February 2024",
    "final": "15 March 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://sites.google.com/unipi.it/fun2024/",
    "title": "FUN",
    "conference": "Fun With Algorithms",
    "location": "La Maddalena Island, Sardinia, Italy",
    "date": "4-8 June 2024",
    "notification": "2 April 2024",
    "final": "15 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.ceid.upatras.gr/webpages/sand2024/",
    "title": "SAND",
    "conference": "Algorithmic Foundations of Dynamic Networks",
    "location": "Patras, Greece",
    "date": "5-7 June 2024",
    "notification": "20 March 2024",
    "final": "2 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://socs24.search-conference.org/",
    "title": "SoCS",
    "conference": "Symposium on Combinatorial Search",
    "location": "Kananaskis, Alberta, Canada",
    "date": "6-8 June 2024",
    "notification": "26 March 2024",
    "final": "10 April 2024",
    "registration": "5 April 2024",
    "remark": ""
  },
  {
    "website": "https://2024.sigmod.org/",
    "title": "PODS",
    "conference": "Principles of Database Systems",
    "location": "Santiago, Chile",
    "date": "9-15 June 2024",
    "notification": "4 March 2024",
    "final": "",
    "registration": "30 April 2024",
    "remark": "co-located with <a href=\"https://2024.sigmod.org/\" target=\"_blank\">SIGMOD</a>"
  },
  {
    "website": "https://2024.sigmod.org/",
    "title": "SIGMOD",
    "conference": "International Conference on Management of Data",
    "location": "Santiago, Chile",
    "date": "9-15 June 2024",
    "notification": "23 February 2024",
    "final": "",
    "registration": "30 April 2024",
    "remark": "co-located with <a href=\"https://2024.sigmod.org/\" target=\"_blank\">PODS</a>"
  },
  {
    "website": "https://ju.se/samarbeta/event-och-konferenser/konferens/scai-symposium-2024/",
    "title": "SCAI",
    "conference": "Scandinavian Conference on AI",
    "location": "Jönköping, Sweden",
    "date": "10-11 June 2024",
    "notification": "28 April 2024",
    "final": "12 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://wollic2024.inf.unibe.ch/",
    "title": "WoLLIC",
    "conference": "Workshop on Logic, Language, Information and Computation",
    "location": "Bern, Switzerland",
    "date": "10-13 June 2024",
    "notification": "15 April 2024",
    "final": "29 April 2024",
    "registration": "10 May 2024",
    "remark": ""
  },
  {
    "website": "http://socg24.athenarc.gr/",
    "title": "SoCG",
    "conference": "Symposium on Computational Geometry",
    "location": "Athens, Greece",
    "date": "11-14 June 2024",
    "notification": "5 February 2024",
    "final": "20 March 2024",
    "registration": "8 May 2024",
    "remark": ""
  },
  {
    "website": "https://swat2024.github.io/website/",
    "title": "SWAT",
    "conference": "Scandinavian Symposium and Workshops on Algorithm Theory",
    "location": "Helsinki, Finland",
    "date": "12-14 June 2024",
    "notification": "2 April 2024",
    "final": "",
    "registration": "18 May 2024",
    "remark": ""
  },
  {
    "website": "https://spaa.acm.org/",
    "title": "SPAA",
    "conference": "Symposium on Parallelism in Algorithms and Architectures",
    "location": "Nantes, France",
    "date": "17-21 June 2024",
    "notification": "7 April 2024",
    "final": "28 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    " confname ": "<a href=\"https://www.podc.org\" target=\"_blank\">PODC</a>\n\t      <span class=\"tooltiptext\">Principles of Distributed Computing</span>",
    "location": "Nantes, France",
    "date": "17-21 June 2024",
    "notification": "22 April 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.discotec.org/2024/",
    "title": "DisCoTec",
    "conference": "Distributed Computing Techniques",
    "location": "Groningen, The Netherlands",
    "date": "17-21 June 2024",
    "notification": "5 April 2024",
    "final": "24 April 2024",
    "registration": "",
    "remark": "federated conference including\n\t      <a href=\"https://www.discotec.org/2024/coordination\" target=\"_blank\">COORDINATION</a>,\n\t      <a href=\"https://www.discotec.org/2024/dais\" target=\"_blank\">DAIS</a>,\n\t      and\n\t      <a href=\"https://www.discotec.org/2024/forte\" target=\"_blank\">FORTE</a>"
  },
  {
    "website": "https://www.discotec.org/2024/coordination",
    "title": "COORDINATION",
    "conference": "Coordination Models and Languages",
    "location": "Groningen, The Netherlands",
    "date": "17-21 June 2024",
    "notification": "5 April 2024",
    "final": "24 April 2024",
    "registration": "",
    "remark": "part of <a href=\"https://www.discotec.org/2024/\" target=\"_blank\">DisCoTec</a>"
  },
  {
    "website": "https://www.discotec.org/2024/dais",
    "title": "DAIS",
    "conference": "Distributed Applications and Interoperable Systems",
    "location": "Groningen, The Netherlands",
    "date": "17-21 June 2024",
    "notification": "5 April 2024",
    "final": "24 April 2024",
    "registration": "",
    "remark": "part of <a href=\"https://www.discotec.org/2024/\" target=\"_blank\">DisCoTec</a>"
  },
  {
    "website": "https://www.discotec.org/2024/forte",
    "title": "FORTE",
    "conference": "Formal Techniques for Distributed Objects, Components, and Systems",
    "location": "Groningen, The Netherlands",
    "date": "17-21 June 2024",
    "notification": "5 April 2024",
    "final": "24 April 2024",
    "registration": "",
    "remark": "part of <a href=\"https://www.discotec.org/2024/\" target=\"_blank\">DisCoTec</a>"
  },
  {
    "website": "https://www.math.aau.at/AofA2024/",
    "title": "AofA",
    "conference": "Probabilistic, Combinatorial, and Asymptotic Methods in the Analysis of Algorithms",
    "location": "Bath, United Kingdom",
    "date": "17-21 June 2024",
    "notification": "28 April 2024",
    "final": "19 May 2024",
    "registration": "3 May 2024",
    "remark": ""
  },
  {
    "website": "https://dl2024.w.uib.no/",
    "title": "DL",
    "conference": "Description Logics",
    "location": "Bergen, Norway",
    "date": "18-21 June 2024",
    "notification": "8 May 2024",
    "final": "3 June 2024",
    "registration": "21 May 2024",
    "remark": ""
  },
  {
    "website": "https://conferences.famnit.upr.si/event/31/",
    "title": "WG",
    "conference": "Graph-Theoretic Concepts in Computer Science",
    "location": "Gozd Martuljek, Slovenia",
    "date": "19-21 June 2024",
    "notification": "19 April 2024",
    "final": "12 July 2024",
    "registration": "30 April 2024",
    "remark": ""
  },
  {
    "website": "http://acm-stoc.org/stoc2024/",
    "title": "STOC",
    "conference": "Symposium on Theory of Computing",
    "location": "Vancouver, Canada",
    "date": "24-28 June 2024",
    "notification": "11 February 2024",
    "final": "31 March 2024",
    "registration": "6 May 2024",
    "remark": ""
  },
  {
    "website": "https://cpm2024.github.io/",
    "title": "CPM",
    "conference": "Combinatorial Pattern Matching",
    "location": "Fukuoka, Japan",
    "date": "25-27 June 2024",
    "notification": "10 April 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://2024.debs.org/",
    "title": "DEBS",
    "conference": "Distributed and Event-Based Systems",
    "location": "Lyon, France",
    "date": "25-28 June 2024",
    "notification": "12 April 2024<br>13 May 2024",
    "final": "24 May 2024",
    "registration": "13 June 2024",
    "remark": ""
  },
  {
    "website": "https://loftconference15.wordpress.com/",
    "title": "LOFT",
    "conference": "Logic and the Foundations of Game and Decision Theory",
    "location": "Bayreuth, Germany",
    "date": "26-28 June 2024",
    "notification": "beginning April",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "http://iwoca2024.di.unisa.it/",
    "title": "IWOCA",
    "conference": "International Workshop on Combinatorial Algorithms",
    "location": "Ischia, Italy",
    "date": "1-4 July 2024",
    "notification": "15 April 2024",
    "final": "26 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://iiia.csic.es/tacl2024/",
    "title": "TACL",
    "conference": "Topology, Algebra, and Categories in Logic",
    "location": "Barcelona, Spain",
    "date": "1-5 July 2024",
    "notification": "20 April 2024",
    "final": "",
    "registration": "",
    "remark": "preceding summer school 25-28 June 2024"
  },
  {
    "website": "https://ijcar2024.loria.fr/",
    "title": "IJCAR",
    "conference": "International Joint Conference on Automated Reasoning",
    "location": "Nancy, France",
    "date": "1-6 July 2024",
    "notification": "28 March 2024",
    "final": "28 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://ipco2024.ii.uni.wroc.pl/",
    "title": "IPCO",
    "conference": "Integer Programming and Combinatorial Optimization",
    "location": "Wrocław, Poland",
    "date": "3-5 July 2024",
    "notification": "26 January 2024",
    "final": "15 March 2024",
    "registration": "31 March 2024",
    "remark": ""
  },
  {
    "website": "https://lics.siglog.org/lics24/",
    "title": "LICS",
    "conference": "Logic in Computer Science",
    "location": "Tallinn, Estonia",
    "date": "8-12 July 2024",
    "notification": "15 April 2024",
    "final": "",
    "registration": "",
    "remark": "co-located with\n\t      <a href=\"https://compose.ioc.ee/icalp2024/#icalp\" target=\"_blank\">ICALP</a>\n\t      and\n\t      <a href=\"https://cs.ioc.ee/fscd24/\" target=\"_blank\">FSCD</a>"
  },
  {
    "website": "https://compose.ioc.ee/icalp2024/#icalp",
    "title": "ICALP",
    "conference": "International Colloquium on Automata, Languages and Programming",
    "location": "Tallinn, Estonia",
    "date": "8-12 July 2024",
    "notification": "14 April 2024",
    "final": "28 April 2024",
    "registration": "",
    "remark": "co-located with\n\t      <a href=\"https://lics.siglog.org/lics24/\" target=\"_blank\">LICS</a>\n\t      and\n\t      <a href=\"https://cs.ioc.ee/fscd24/\" target=\"_blank\">FSCD</a>"
  },
  {
    "website": "https://events.illc.uva.nl/CiE/CiE2024/",
    "title": "CiE",
    "conference": "Computability in Europe",
    "location": "Amsterdam, The Netherlands",
    "date": "8-12 July 2024",
    "notification": "20 April 2024",
    "final": "1 May 2024",
    "registration": "20 May 2024",
    "remark": ""
  },
  {
    "website": "https://csf2024.ieee-security.org/",
    "title": "CSF",
    "conference": "Computer Security Foundations",
    "location": "Enschede, The Netherlands",
    "date": "8-12 July 2024",
    "notification": "7 April 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://conf.researchr.org/home/staf-2024/ecmfa-2024",
    "title": "ECMFA",
    "conference": "European Conference on Modelling Foundations and Applications",
    "location": "Enschede, The Netherlands",
    "date": "8-12 July 2024",
    "notification": "10 April 2024<br>5 June 2024",
    "final": "",
    "registration": "",
    "remark": "part of <a href=\"https://conf.researchr.org/home/staf-2024\" target=\"_blank\">STAF</a>"
  },
  {
    "website": "https://conf.researchr.org/home/icgt-2024",
    "title": "ICGT",
    "conference": "International Conference on Graph Transformation",
    "location": "Enschede, The Netherlands",
    "date": "8-12 July 2024",
    "notification": "23 April 2024",
    "final": "14 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://cs.ioc.ee/fscd24/",
    "title": "FSCD",
    "conference": "Formal Structures for Computation and Deduction",
    "location": "Tallinn, Estonia",
    "date": "10-13 July 2024",
    "notification": "22 April 2024",
    "final": "6 May 2024",
    "registration": "",
    "remark": "co-located with\n\t      <a href=\"https://compose.ioc.ee/icalp2024/#icalp\" target=\"_blank\">ICALP</a>\n\t      and\n\t      <a href=\"https://lics.siglog.org/lics24/\" target=\"_blank\">LICS</a>"
  },
  {
    "website": "https://gecco-2024.sigevo.org/",
    "title": "GECCO",
    "conference": "Genetic and Evolutionary Computation Conference",
    "location": "Melbourne, Australia",
    "date": "14-18 July 2024",
    "notification": "21 March 2024",
    "final": "11 April 2024",
    "registration": "10 May 2024",
    "remark": ""
  },
  {
    "website": "https://antsmath.org/ANTSXVI/",
    "title": "ANTS",
    "conference": "Algorithmic Number Theory Symposium",
    "location": "Cambridge, Massachusetts, USA",
    "date": "15-19 July 2024",
    "notification": "April 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.utwente.nl/en/eemcs/fois2024/",
    "title": "FOIS",
    "conference": "Formal Ontology in Information Systems",
    "location": "Enschede, The Netherlands",
    "date": "8-9 July 2024 (online)<br>15-19 July 2024 (on site)",
    "notification": "10 May 2024",
    "final": "",
    "registration": "3 June 2024",
    "remark": ""
  },
  {
    "website": "https://www.issac-conference.org/2024/",
    "title": "ISSAC",
    "conference": "International Symposium on Symbolic and Algebraic Computation",
    "location": "Raleigh, North Carolina, USA",
    "date": "16-19 July 2024",
    "notification": "16/30 April 2024",
    "final": "21 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://icdcs2024.icdcs.org/",
    "title": "ICDCS",
    "conference": "International Conference on Distributed Computing Systems",
    "location": "Jersey City, New Jersey, USA",
    "date": "16-19 July 2024",
    "notification": "12 April 2024",
    "final": "10 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://icml.cc/",
    "title": "ICML",
    "conference": "International Conference on Machine Learning",
    "location": "Vienna, Austria",
    "date": "21-27 July 2024",
    "notification": "1 May 2024",
    "final": "29 May 2024",
    "registration": "15 June 2024",
    "remark": ""
  },
  {
    "website": "https://computationalcomplexity.org/",
    "title": "CCC",
    "conference": "Computational Complexity Conference",
    "location": "Ann Arbor, Michigan, USA",
    "date": "22-25 July 2024",
    "notification": "5 May 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "http://i-cav.org/2024/",
    "title": "CAV",
    "conference": "Computer-Aided Verification",
    "location": "Montreal, Canada",
    "date": "22-27 July 2024",
    "notification": "26 March 2024<br>10 May 2024",
    "final": "19 May 2024",
    "registration": "",
    "remark": "submissions updated until 26 January 2024<br>artifact submission: 8 April 2024 (mandatory for tool papers)"
  },
  {
    "website": "https://sea2024.univie.ac.at/",
    "title": "SEA",
    "conference": "Symposium on Experimental Algorithms",
    "location": "Vienna, Austria",
    "date": "23-26 July 2024",
    "notification": "27 March 2024",
    "final": "28 April 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://tase2024.github.io/",
    "title": "TASE",
    "conference": "Theoretical Aspects of Software Engineering",
    "location": "Guiyang, China",
    "date": "29 July - 1 August 2024",
    "notification": "10 April 2024",
    "final": "10 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://ijcai24.org/",
    "title": "IJCAI",
    "conference": "International Joint Conference on Artificial Intelligence",
    "location": "Jeju Island, South Korea",
    "date": "3-9 August 2024",
    "notification": "22 February 2024<br>16 April 2024",
    "final": "",
    "registration": "",
    "remark": "appendix and resubmission until 24 January 2024"
  },
  {
    "website": "https://cicm-conference.org/2024/",
    "title": "CICM",
    "conference": "Conference on Intelligent Computer Mathematics",
    "location": "Montréal, Québec, Canada",
    "date": "5-9 August 2024",
    "notification": "28 May 2024",
    "final": "11 June 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://events.gwdg.de/event/576/",
    "title": "DLT",
    "conference": "Developments in Language Theory",
    "location": "Göttingen, Germany",
    "date": "12-16 August 2024",
    "notification": "3 May 2024",
    "final": "17 May 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://crypto.iacr.org/2024/",
    "title": "CRYPTO",
    "conference": "CRYPTO",
    "location": "Santa Barbara, California, USA",
    "date": "18-22 August 2024",
    "notification": "7 April 2024<br>3 May 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://ramics-conf.github.io/2024/",
    "title": "RAMiCS",
    "conference": "Relational and Algebraic Methods in Computer Science",
    "location": "Prague, Czech Republic",
    "date": "19-23 August 2024",
    "notification": "21 May 2024",
    "final": "22 June 2024",
    "registration": "",
    "remark": "co-located with <a href=\"https://www.cs.cas.cz/aiml2024/\" target=\"_blank\">AiML</a>"
  },
  {
    "website": "https://www.cs.cas.cz/aiml2024/",
    "title": "AiML",
    "conference": "Advances in Modal Logic",
    "location": "Prague, Czech Republic",
    "date": "19-23 August 2024",
    "notification": "20 May 2024",
    "final": "21 June 2024",
    "registration": "",
    "remark": "co-located with <a href=\"https://ramics-conf.github.io/2024/\" target=\"_blank\">RAMiCS</a>"
  },
  {
    "website": "http://satisfiability.org/SAT24/",
    "title": "SAT",
    "conference": "Theory and Applications of Satisfiability Testing",
    "location": "Pune, India",
    "date": "21-24 August 2024",
    "notification": "22 May 2024",
    "final": "22 June 2024",
    "registration": "",
    "remark": "preceded 18-20 August 2024 by Indian SAT+SMT School"
  },
  {
    "website": "https://anl.sjtu.edu.cn/cocoon2024/",
    "title": "COCOON",
    "conference": "Computing and Combinatorics Conference",
    "location": "Shanghai, China",
    "date": "23-25 August 2024",
    "notification": "25 May 2024",
    "final": "10 June 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://kdd2024.kdd.org/",
    "title": "KDD",
    "conference": "Knowledge Discovery and Data Mining",
    "location": "Barcelona, Spain",
    "date": "25-29 August 2024",
    "notification": "16 May 2024",
    "final": "4 June 2024",
    "registration": "10 July 2024",
    "remark": ""
  },
  {
    "website": "https://2024.euro-par.org/",
    "title": "Euro-Par",
    "conference": "European Conference on Parallel and Distributed Computing",
    "location": "Madrid, Spain",
    "date": "26-30 August 2024",
    "notification": "29 April 2024",
    "final": "2 June 2024",
    "registration": "30 June 2024",
    "remark": ""
  },
  {
    "website": "https://patatconference2024.dtu.dk/",
    "title": "PATAT",
    "conference": "Practice and Theory of Automated Timetabling",
    "location": "Lyngby, Denmark",
    "date": "27-30 August 2024",
    "notification": "3 May 2024",
    "final": "24 June 2024",
    "registration": "24 June 2024",
    "remark": ""
  },
  {
    "website": "https://www.scss-conference.org/",
    "title": "SCSS",
    "conference": "Symbolic Computation in Software Science",
    "location": "Tokyo, Japan",
    "date": "28-30 August 2024",
    "notification": "1 May 2024",
    "final": "15 June 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://algo-conference.org/2024/",
    "title": "ALGO",
    "conference": "ALGO",
    "location": "Egham, United Kingdom",
    "date": "2-6 September 2024",
    "notification": "",
    "final": "",
    "registration": "",
    "remark": "federated conference including\n\t      <a href=\"https://algo-conference.org/2024/algocloud/\" target=\"_blank\">ALGOCLOUD</a>,\n\t      <a href=\"https://algo-conference.org/2024/esa/\" target=\"_blank\">ESA</a>,\n\t      <a href=\"https://algo-conference.org/2024/ipec/\" target=\"_blank\">IPEC</a>,\n\t      <a href=\"https://algo-conference.org/2024/atmos/\" target=\"_blank\">ATMOS</a>,\n\t      <a href=\"https://algo-conference.org/2024/wabi/\" target=\"_blank\">WABI</a>"
  },
  {
    "website": "https://icfp24.sigplan.org/",
    "title": "ICFP",
    "conference": "International Conference on Functional Programming",
    "location": "Milan, Italy",
    "date": "2-7 September 2024",
    "notification": "20 May 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.viam.science.tsu.ge/itp2024/",
    "title": "ITP",
    "conference": "Interactive Theorem Proving",
    "location": "Tbilisi, Georgia",
    "date": "9-14 September 2024",
    "notification": "20 May 2024",
    "final": "10 June 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.safecomp2024.unifi.it/",
    "title": "SAFECOMP",
    "conference": "Computer Safety, Reliability and Security",
    "location": "Florence, Italy",
    "date": "17-20 September 2024",
    "notification": "21 April 2024",
    "final": "1 June 2024",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://www.sigsac.org/ccs/CCS2024/",
    "title": "CCS",
    "conference": "Computer and Communication Security",
    "location": "Salt Lake City, Utah, USA",
    "date": "14-18 October 2024",
    "notification": "3 April 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {
    "website": "https://focs.computer.org/2024/",
    "title": "FOCS",
    "conference": "Foundations of Computer Science",
    "location": "Chicago, Illinois, USA",
    "date": "27-30 October 2024",
    "notification": "1 July 2024",
    "final": "",
    "registration": "",
    "remark": ""
  },
  {}
];